spring:
  datasource:
    url: jdbc:postgresql://algashop-postgres:5432/template
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    url: jdbc:postgresql://algashop-postgres:5432/template

