spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/template

